### ISSUE TITLE
Hyphens should be allowed in author names

### ISSUE THREAD

**Issue by alsuhr-c** [lil-lab/recnet#100]
<img width="662" alt="Screen Shot 2024-01-26 at 17 31 07" src="https://github.com/lil-lab/recnet/assets/20176003/66549515-f456-43de-8dec-261c2491e57e">
Removing the hyphen in the penultimate author's name fixes the warning.

**Comment by yoavartzi** [comment]
Not sure this is still an issue. The buggy code might have been in the frontend, and didn't survive the overhaul. @swh00tw any idea?

**Comment by swh00tw** [comment]
> Not sure this is still an issue. The buggy code might have been in the frontend, and didn't survive the overhaul. @swh00tw any idea?

Now, this issue no longer exists. It's because the previous frontend version has some validation code for this field (not perfect tho).

In this new version, I did not add any checks or validation for this field. Therefore, the issue disappeared.

**Comment by swh00tw** [comment]
Btw, do you think we need to add back some validation logic for this field?

**Comment by yoavartzi** [comment]
Closing this issue, and opened #134 because some fields that shouldn't be are now optional
