### ISSUE TITLE
Investigate migration to new framework

### ISSUE THREAD

**Issue by yoavartzi** [lil-lab/recnet#101]
Next.js frontend
Server backend (EC2 on AWS)
Maybe RDS for database

**Comment by yoavartzi** [comment]
- Create a bunch of issues for migration
- Cost estimates of AWS/EC2/RDS

**Comment by joannechen1223** [comment]
[Migration Plan](https://www.notion.so/Backend-Migration-Plan-b3948291f9e642c4a990ee266431929d?pvs=4)
