### ISSUE TITLE
Migrate user authentication

### ISSUE THREAD

**Issue by joannechen1223** [lil-lab/recnet#109]

**Comment by yoavartzi** [comment]
@joannechen1223 probably authentication is not something we want to change at this point, especially because other services will create additional costs, which I wish to avoid when not needed

**Comment by yoavartzi** [comment]
See #91 for related discussion (not critical)

**Comment by yoavartzi** [comment]
Is this something we still need? What's the current state of affairs with authentication?

**Comment by swh00tw** [comment]
We are using Firebase as auth provider now. I think it's good to close this now since we are not planning to migrate to other provider. We can reopen if we need.
