### ISSUE TITLE
FAQ page fixes

### ISSUE THREAD

**Issue by yoavartzi** [lil-lab/recnet#115]
Please make the following changes:
- [x] Add the video from the About page to the FAQ page as well
- [x]  Rename FAQ to Help
- [x] Change "How to use it?" -> "How does Recnet work?"
- [x] Fix the local time we display. It's currently buggy 
<img width="848" alt="image" src="https://github.com/lil-lab/recnet/assets/3289873/2281b73e-0db6-40df-b3df-986d1d991fab">

**Comment by swh00tw** [comment]
> Add the video from the About page to the FAQ page (Now it's Help Page) as well

I feel like it's a little weird to have the same video appear twice. Any specific reason why to do so?

**Comment by yoavartzi** [comment]
Currently, it actually appears three times. Recnet is really new, and this video briefly explains what it is about (I will create a new one soon, but we should use this one for now)

We also had it on the front page. I like the cleaner look now, but for folks who haven't logged in yet, it all looks really opaque. So actually we should add it there too
