### ISSUE TITLE
Fix how we present recs with the new UI

### ISSUE THREAD

**Issue by yoavartzi** [lil-lab/recnet#118]
Recommendations should be focused on the paper first. In the future, we will unify rec entries from multiple people you follow if they recommend the same item in the same cycle feed.

Concretely, lets re-arrange the elements to the rough mockup below (the current style is great, the mockup is just for arrangement). We only need the date on a rec (i.e., "Yilun Hua recommended on 2/1/24:...") when there are multiple dates on a page (i.e., user profile), but not when there is a single date (i.e., a feed for a specific cycle). 

<img width="927" alt="image" src="https://github.com/lil-lab/recnet/assets/3289873/a39d3754-b412-4da2-a3ef-85c0684ed272">

**Comment by swh00tw** [comment]
Sounds good. Will create another pull request to resolve this issue!

**Comment by yoavartzi** [comment]
Sounds Good. But let's prioritize that. This is actually a very important design decision. Thanks!

**Comment by swh00tw** [comment]
> Sounds Good. But let's prioritize that. This is actually a very important design decision. Thanks!

Ok. Will work on this this week.

**Comment by yoavartzi** [comment]
While we are doing this, we should make sure this visual bug doesn't repeat. Happens when names need to wrap

<img width="434" alt="image" src="https://github.com/lil-lab/recnet/assets/3289873/c4c286c0-886c-47e8-ba8b-3378fec18038">
<img width="505" alt="image" src="https://github.com/lil-lab/recnet/assets/3289873/6e34ad01-c1d2-44ee-9dc2-bd86299ae227">

**Comment by swh00tw** [comment]
![Screenshot 2024-02-16 at 11 13 04 AM](https://github.com/lil-lab/recnet/assets/71842426/4fa5214f-aa47-4ece-97da-5691263390ac)

From top to bottom:
1. Rec Card (without showing the date)  (in `/feed` page)
2. Rec Card when multiple people rec the same paper  (in `/feed` page)
3. Rec Card at user profile page (show the date)

**Comment by swh00tw** [comment]
@yoavartzi let me know what you think about the new design!

**Comment by yoavartzi** [comment]
This is really great!
 
I suspect in the future we might want to make the lower half a bit more compact, but that will be an issue only if we get more traffic and figure out a few more features. 

Let's deploy this. Thanks!
