### ISSUE TITLE
Integrate third-party search provider

### ISSUE THREAD

**Issue by anya-ji** [lil-lab/recnet#12]
Firebase doesn't support full-text elastic search, which we need for a better search experience in the app.
Currently, a basic version for searching for users is implemented at `pages/api/user/search.js`.

Firebase recommends these few options for elastic search:
https://firebase.google.com/docs/firestore/solutions/search?provider=elastic

Compared to the other two, I recommend using Typesense - it's lightweight, straightforward in implementation, and the best in pricing, integration (through [Firebase extension](https://github.com/typesense/firestore-typesense-search)), and option to self-host or pay for Typesense cloud.

**Comment by yoavartzi** [comment]
Current search is much better, so can skip for now
