### ISSUE TITLE
Date format bug on mobile

### ISSUE THREAD

**Issue by yoavartzi** [lil-lab/recnet#124]
The cutoff date is displayed YYYY/MM/DD, which is really weird and non standard

![image](https://github.com/lil-lab/recnet/assets/3289873/98b9c49d-ca2a-4cf7-8ce9-558b7e26786c)

**Comment by swh00tw** [comment]
I didn't see the behavior you described in the image. Could you elaborate more, please?

**Comment by swh00tw** [comment]
![Screenshot 2024-02-12 at 4 13 23 PM](https://github.com/lil-lab/recnet/assets/71842426/3d8ed162-2ab7-4de1-8355-93d26daa3f57)

It's MM/DD/YYYY

**Comment by yoavartzi** [comment]
Sorry, wrong screenshot


See cutoff on top-right

![image](https://github.com/lil-lab/recnet/assets/3289873/463045b8-30b9-4e30-be21-f4534c179152)
