### ISSUE TITLE
Better font sizing 

### ISSUE THREAD

**Issue by yoavartzi** [lil-lab/recnet#127]
Increase the font size throughout the system a bit. It's a tad too small.

Add controls for font size that are stored in the user profile and are applied through all devices for that user.

**Comment by swh00tw** [comment]
Okay, I will adjust the font size. 

Letting users configure the preferred font size is a good idea. To apply the same setting for all devices which means we need to store this configuration in the database for each user. It might take a few days to do this. 

Therefore, I will close this issue after I finish adjusting the font size. As for letting users set the font size somewhere in the app, I suggest we should open another issue.
