### ISSUE TITLE
Char count of tl;dr not automatically updated after edits

### ISSUE THREAD

**Issue by annshin** [lil-lab/recnet#131]
**OS**: Mac Sonoma 14.1.2
**Browser**: Google Chrome Version 121.0.6167.160 (Official Build) (x86_64)

**Issue description**: 
In the `tl;dr` field, when I'm editing the text, the character count is not automatically updated in real time. 

I need to either:
- (1) click on a blank space somewhere else on the page, or
- (2) cut and repaste the entire text for the count to refresh. 

(1) does not always work - it works for the first edit, but if I continue to do edits and then do clicks, the count is still not updated. If I switch to a different tab then come back, the count is again updated.

![Screenshot 2024-02-13 at 14 18 22](https://github.com/lil-lab/recnet/assets/10830620/9c80725e-b412-4e51-9cd7-8a0cd3b70de6)

**Comment by swh00tw** [comment]
thanks for reporting the bug, will investigate this these days
