### ISSUE TITLE
Buggy text alignment for institution in user card components

### ISSUE THREAD

**Issue by yoavartzi** [lil-lab/recnet#135]
See the difference alignment between for the institution 🏠 between the two cards in the screenshot below. Seems related to length of string

<img width="272" alt="image" src="https://github.com/lil-lab/recnet/assets/3289873/37ab4d58-dbee-4837-88ef-315a0918ae69">

**Comment by swh00tw** [comment]
Got it. Yeah, long length of string causes lots of UI bug😵. I'll make sure to test this kind of case in the future.
