### ISSUE TITLE
Shuffle All Users page and empty search response

### ISSUE THREAD

**Issue by yoavartzi** [lil-lab/recnet#140]
Let's shuffle the All User page (https://www.recnet.io/all-users) and what you get in response to an empty search. Regular search should be ordered.

The shuffle should be consistent per user, so can do it like we shuffle the order of recs in the feed.

Thanks

**Comment by yoavartzi** [comment]
@swh00tw can you prioritize that? Should be pretty simple, and it impacts how users start to interact with the system. Thanks!

**Comment by swh00tw** [comment]
Ok, I'll finish it today.

**Comment by swh00tw** [comment]
I've created a PR, I'll merge it today or tomorrow after Joanne approved @joannechen1223
