### ISSUE TITLE
Integrate conventional analytics (e.g., Google Analytics)

### ISSUE THREAD

**Issue by yoavartzi** [lil-lab/recnet#149]
How hard is it for us to integrate Google Analytics? @swh00tw 
To get a general idea of traffic

**Comment by swh00tw** [comment]
Not hard actually. I've done it before (wasn't the latest Google Analytics version tho. Back then, it was called Universal Analytics (UA) and it's deprecated now.)

Anyway, I've created a PR to add GA to our app.

**Comment by swh00tw** [comment]
![Screenshot 2024-02-29 at 1 18 28 AM](https://github.com/lil-lab/recnet/assets/71842426/d55788f6-e159-4ad4-b6bb-1f2cdcc6e00a)

It's working now and I've sent you an invitation email for GA.
