### ISSUE TITLE
Migrating Google analytics to recnet.io account

### ISSUE THREAD

**Issue by yoavartzi** [lil-lab/recnet#159]
Please migrate Google Analytics from the Gmail account to be under the recnet.io Google identity

**Comment by swh00tw** [comment]
Done. But I am not sure if you can access GA now. Do I need to send you another invitation?
![Screenshot 2024-03-01 at 2 50 15 PM](https://github.com/lil-lab/recnet/assets/71842426/20897b31-830c-4120-aeb9-1b1feea48fd8)

**Comment by yoavartzi** [comment]
Yes, please send again. Thanks!
- Yoav

**Comment by swh00tw** [comment]
I am not sure which account to send. Can you provide the email addr?
