### ISSUE TITLE
Add logo to top-left and browser tab

### ISSUE THREAD

**Issue by yoavartzi** [lil-lab/recnet#226]
I would like to add a logo to the tab icon, and on the left of the website name on the top left.

**Comment by swh00tw** [comment]
duplicated issue #93 ?

**Comment by yoavartzi** [comment]
Not exactly, because that one was just for coming up with a logo. I will close #93

**Comment by yoavartzi** [comment]
We need a favico too using the same visual

**Comment by swh00tw** [comment]
<img width="200" alt="Screenshot 2024-04-30 at 10 28 37 AM" src="https://github.com/lil-lab/recnet/assets/71842426/51319a39-88c0-4268-aa57-5813ce34ee55">

Yeah I've added. It's not showing up in your browser? Maybe clear cache and try again.

**Comment by yoavartzi** [comment]
Indeed. Thanks!
