### ISSUE TITLE
Announcement popup on top of feed page

### ISSUE THREAD

**Issue by yoavartzi** [lil-lab/recnet#227]
Add an admit option to set an alert to appear at the top of the feed page, similar to the one we had we had when the email digest was down. The admin can set the alert content. If there's no content, there's no alert.

**Comment by joannechen1223** [comment]
First version backend design: https://www.notion.so/Announcement-DB-schema-API-0b6d6f4c28334f3684116219992578bb

**Comment by yoavartzi** [comment]
Looks really good!
