### ISSUE TITLE
Add "verified" flag to paper records

### ISSUE THREAD

**Issue by yoavartzi** [lil-lab/recnet#252]
Add a binary "verified" flag to paper records. This flag should be set when the record for the paper is created. 

When the details are entered through the interface, the flag should be FALSE

We will use this flag later to mark papers that come from moderated sources, like arXiv (once we put the integration in place)

**Comment by joannechen1223** [comment]
We already have "isVerified" flag for each paper. It is a boolean value default to be `false`

**Comment by yoavartzi** [comment]
Perfect
