### ISSUE TITLE
arXiv meta data retrieval

### ISSUE THREAD

**Issue by yoavartzi** [lil-lab/recnet#256]
Implement arXiv as an information provider (see #254).

arXiv will be a verified provider, so all records retrieved from arXiv will be verified (see #252).

Need to study the arXiv API:
https://info.arxiv.org/help/api/index.html

**Comment by yoavartzi** [comment]
The arXiv service should also normalize the URL. arXiv URLs can point to PDF (https://arxiv.org/pdf/2408.01417) or abstract (https://arxiv.org/abs/2408.01417). We should process PDF URLs to point to the abstract page

**Comment by yoavartzi** [comment]
It important o take into account that arXiv also adds versioning information to the URL, when the a specific version is linked to

**Comment by joannechen1223** [comment]
This feature has already been released to production. Let me know if there are any bugs.
