### ISSUE TITLE
Add URLs directly to a recommendation

### ISSUE THREAD

**Issue by yoavartzi** [lil-lab/recnet#258]
I would like to add permalinks directly to recommendations.

1. We need to design a rec-specific web page (or do we go to the user page and simply scroll to the rec)
2. The link should be copyable from from a rec card
3. The link should have an informative and nice-looking social/slack preview

A good example for social/slack preview is what arXiv does for abstract pages, for example in Slack:
<img width="775" alt="image" src="https://github.com/user-attachments/assets/58e6e9e6-c0fb-4452-bbde-fff51fb52378">

**Comment by swh00tw** [comment]
![Screenshot 2024-08-27 at 11 58 56 PM](https://github.com/user-attachments/assets/7471ae9d-496e-48f0-9222-ef05cfc52a96)

Look good to you?

**Comment by yoavartzi** [comment]
I think the last comment is referring to another issue -> #257 
Right? 
With regard to #257, it looks good. Thanks!

**Comment by swh00tw** [comment]
Ohh right, I was referring #257.
