### ISSUE TITLE
Updates to about page

### ISSUE THREAD

**Issue by yoavartzi** [lil-lab/recnet#265]
1. Let's remove the video from the about page
2. Edit sentence "The RecNet mechanism was initially outlined by Yoav Artzi in a [Substack post](https://yoavartzi.substack.com/p/a-quick-sketch-of-a-human-based-paper)." -> "The RecNet mechanism was initially outlined [here](https://yoavartzi.com/log/human-driven-paper-rec.html)."
3. Remove the horizontal bar between the sections
4. Add the following sentence after the first paragraph and before the "team" section: "The [help page](/help) includes instructions on how to get started, including a short introduction video."
5. Make sure the "team" header is h2, so one size smaller than the header of the entire page

**Comment by yoavartzi** [comment]
This is too small :)
I can't figure anything from the video when it's embedded this size

**Comment by swh00tw** [comment]
Got it. I've created a new PR to resize.
Testing link: https://rec-net-git-chore-resize-intro-video-recnet-542617e7.vercel.app/
Lmk if you want it bigger or it's enough.

**Comment by yoavartzi** [comment]
Looks great. Thanks!

- Yoav
