### ISSUE TITLE
Mark self-recommendations in the weekly digest

### ISSUE THREAD

**Issue by yoavartzi** [lil-lab/recnet#272]
We should mark self-recommendations in the weekly digest. This should apply generally to various digest mediums (currently only email, but later Slack as well).

**Comment by yoavartzi** [comment]
This doesn't seem to work, or at least didn't show in the email digest tonight
<img width="632" alt="image" src="https://github.com/user-attachments/assets/8ddbf29e-671c-4bc2-b59c-c21e75de88bd">

**Comment by swh00tw** [comment]
Oh, I guess that's because I pushed the new email template to main branch but we forget to trigger backend rebuild

**Comment by swh00tw** [comment]
![Screenshot 2024-10-01 at 8 46 51 PM](https://github.com/user-attachments/assets/dd3e35ad-6c77-406d-ba18-dab4906bff60)

Fixed.
