### ISSUE TITLE
arXiv links normalization and HTML detection

### ISSUE THREAD

**Issue by yoavartzi** [lil-lab/recnet#298]
PDF links should normalize to abs links:
<img width="295" alt="image" src="https://github.com/user-attachments/assets/95dbe53c-7872-4e56-a10f-1c57dd8d730e">

HTML links are not detected:
<img width="328" alt="image" src="https://github.com/user-attachments/assets/de1470d4-929e-4da0-b107-6e7d5bf0de4c">

HTML links should also be normalized to abs links

**Comment by joannechen1223** [comment]
Updated the regex to `https?:\/\/arxiv\.org\/(abs|pdf|html)\/(?<id>[0-9.]+(v[0-9]+)?)` to address html case.

**Comment by yoavartzi** [comment]
Need to fix on frontend to take the link @swh00tw
