### ISSUE TITLE
Announcement text not aligned well

### ISSUE THREAD

**Issue by yoavartzi** [lil-lab/recnet#300]
<img width="770" alt="image" src="https://github.com/user-attachments/assets/73d82250-2128-47ee-b874-c2cd9d939796">

It just doesn't extend all the way to the right :/

**Comment by swh00tw** [comment]
![Screenshot 2024-10-02 at 12 23 17 PM](https://github.com/user-attachments/assets/ad34a5ff-867e-4380-879b-6496908d3d89)

Looks good in prod now
