### ISSUE TITLE
Add link to invite code request form on signup page

### ISSUE THREAD

**Issue by yoavartzi** [lil-lab/recnet#316]
Add link to the invite code request form just under the invite code field in sign up

<img width="1295" alt="image" src="https://github.com/user-attachments/assets/d7d5fd40-af5d-4470-9d43-2624f6c02458">

**Comment by yoavartzi** [comment]
@swh00tw this should be really quick. Can you prioritize this for the next day or two? Thanks!

**Comment by swh00tw** [comment]
![Screenshot 2024-10-03 at 12 01 54 AM](https://github.com/user-attachments/assets/849701c5-3042-40e4-8b6f-d126ba16839e)

Actually, I think put it here would look better. What do you think? The wording can be modified tho. Any thought?

**Comment by yoavartzi** [comment]
Yea, much better than my suggestion. Thanks!
