### ISSUE TITLE
Consistent shuffling of recommendations in the feed

### ISSUE THREAD

**Issue by yoavartzi** [lil-lab/recnet#36]
Papers should be shuffled for each user independently. The shuffling should be random, but consistent. So everytime a user views a feed from a specific cycle they should get the same ordering. Different users should get different random ordering. 

Proposal on how to do it:
Each user gets allocated a secret random seed when they create their account (--> #37 ). The seed is created once on account creation, and is not modified afterwards. The seed is not visible to the user. Given a list of papers to display, we shuffle them based on the seed. For example, something like this might work:
https://stackoverflow.com/a/53758827
Or maybe this:
https://stackoverflow.com/a/28256743

**Comment by anya-ji** [comment]
@vtjong you could use the Chance package that seems to be able to take a string as a seed: https://chancejs.com/usage/seed.html
