### ISSUE TITLE
Following page: back to profile link

### ISSUE THREAD

**Issue by anya-ji** [lil-lab/recnet#58]
We might need to slightly redesign the following page when there are more users. The back-to-profile link is currently at the bottom of the list, but as we have more users, we would want to either make it e.g. an arrow at the top left, or paginate the infinite scroll list.

**Comment by yoavartzi** [comment]
There should be a back button at the top
Not like how it looks now


![Image](https://github.com/lil-lab/recnet/assets/3289873/e312694f-f00d-4386-baf5-41e66c9e002c)

**Comment by swh00tw** [comment]
Close after #112 merged
