### ISSUE TITLE
Consider emoji reactions

### ISSUE THREAD

**Issue by yoavartzi** [lil-lab/recnet#60]
Consider adding a very limited reaction channel to allow readers to relay feedback to the recommender.
Current proposal:
- Identify emoji reactions that we want to enable (include all of: 👍 🤔 😮 😭 🤩 🤯 👀 🚀 ❤️ 🙏 🎉)
  - Build in scalable way so we can add  
- Followers can click any subset of them to relay a reaction, clicking again unselects a reaction
- ~The followers don't see reaction counts~
- ~Only the recommender sees reaction counts, but does not see who reacted (does not see any associated user names)~
- Everyone case see reaction counts, but not who reacted 
- You can only react on an emoji once, or unreact (like Slack)
- You can react with multiple emojis

**Comment by joannechen1223** [comment]
Design Doc: https://www.notion.so/Rec-Emoji-Reaction-ad4c0db048574a6183a672b25d209e5c
