### ISSUE TITLE
SMTP password create secret error

### ISSUE THREAD

**Issue by anya-ji** [lil-lab/recnet#82]
When setting up the email extension in Firestore, creating secret for the SMTP password fails with a generic error. Current solution is to include the password in the SMTP connection URI and it works fine, but it's better to use a secret.

To reconfigure this: Firebase project > recnet > Extensions > Trigger Email from Firebase > Extension configuration

**Comment by yoavartzi** [comment]
@swh00tw @joannechen1223 Is this still an issue with the new backend? If not, please close this bug. Thanks!

**Comment by swh00tw** [comment]
Since we are deprecating Firebase email service and replace by our email service, I think this can be closed. cc @joannechen1223
