### ISSUE TITLE
Adapt email digest formatting to new design

### ISSUE THREAD

**Issue by yoavartzi** [lil-lab/recnet#87]
Adjust the email digest formatting to align with the new UI

**Comment by yoavartzi** [comment]
![Image](https://github.com/lil-lab/recnet/assets/3289873/3a6e997a-5a9d-4526-bddd-9a50098729c7)

**Comment by yoavartzi** [comment]
We just need to update the colors to match the new design

**Comment by yoavartzi** [comment]
@swh00tw are we going to deploy this soon? I remember you showed me a really nice new design, but I think it is still not out there. Thanks!

**Comment by swh00tw** [comment]
> @swh00tw are we going to deploy this soon? I remember you showed me a really nice new design, but I think it is still not out there. Thanks!

Yes, we are going to deploy it soon. I deployed last week but encountered some technical issues. I created another PR #152  to fix it and hopefully, we can see the new design in our inbox next week.

**Comment by yoavartzi** [comment]
Sounds good. Thanks!

**Comment by swh00tw** [comment]
Deployed
