### ISSUE TITLE
Deactivate account

### ISSUE THREAD

**Issue by yoavartzi** [lil-lab/recnet#90]
We need a way to deactivate an account. When an account is deactivated, it receives no emails, and when logging in it can only see a page saying the account has been deactivated and with a button to re-activate it. Deactivation is probably done via  flag on the account. 

When an account is deactivated:
- Others can't follow or unfollow it
- The account is not counted as following or being followed by other accounts
- It has no profile page
- We still store all its connections and past recommendations
- The user receives no emails or any communication 
- It can't recommend papers, see the recommendation feed, etc
- When logging in, the user sees a page with a message saying the account has been deactivated, and the user is asked if to re-activate the account or logout.

When an account is re-activate, it gets back all its followers and followings.

**Comment by joannechen1223** [comment]
Backend design: https://www.notion.so/Deactivate-Account-6f43ae29772442e293d8f0d9641d2be1

**Comment by yoavartzi** [comment]
Looks great.

- Yoav
