### ISSUE TITLE
Firebase authentication migration

### ISSUE THREAD

**Issue by anya-ji** [lil-lab/recnet#91]
Migrate Firebase project to the new org

**Comment by yoavartzi** [comment]
@anya-ji Maybe this should wait while @joannechen1223 is migrating most of the DB functionality to a postgres SQL server. I hope this will happen over the next few weeks. Then there's the issue of authentication, which is somehow also connected to Firebase, so I am not completely sure.

**Comment by anya-ji** [comment]
Yes, auth can be reconfigured by simply changing the config file to the new org's project configs. Another thing attached to the Cornell firebase account is email. It just needs a reconfiguration and redeployment of the cloud function on the new org's project console as well. Ofc I don't think we actually need to do these at all if these two functionalities are going to be moved away from firebase as well.

**Comment by yoavartzi** [comment]
Any idea how authentication migration is going to influence existing accounts? If it's going to effect them.

**Comment by anya-ji** [comment]
They might be logged out and just need to log in again. The recnet accounts won't be affected because they are stored in the database.

**Comment by yoavartzi** [comment]
@joannechen1223 can you look into it as part of the broader migration project? We need to continue using Google Authentication, but integrate it into our new backend, or at the least move it away from Anya's accounts after we migrate away from Firebase for everything else. Thanks!

**Comment by anya-ji** [comment]
I don't think anything is under my account, so anyone from Cornell added to this project can access/own it. It's just that the project is under the Cornell organization which might be inconvenient in the long run.

**Comment by yoavartzi** [comment]
Right. I forgot that it's under the Cornell org. Thanks!

**Comment by yoavartzi** [comment]
Closing this issue for now. We will figure out authentication soon enough. Thanks!
