### ISSUE TITLE
Identify websites for design inspiration

### ISSUE THREAD

**Issue by yoavartzi** [lil-lab/recnet#92]
Identify a set of websites showing different design languages as options to inspire our design. 

Please list the websites in comments below, ideally with a screenshot or two. For example, BlueSky is one good option.

**Comment by yoavartzi** [comment]
BlueSky (https://bsky.app/)

<img width="1261" alt="image" src="https://github.com/lil-lab/recnet/assets/3289873/be7c97bd-c0e2-4e11-a720-e77eaefaa8fa">

<img width="1253" alt="image" src="https://github.com/lil-lab/recnet/assets/3289873/2d9eba5a-bd2d-4a3f-8096-852f459f0ef2">

**Comment by swh00tw** [comment]
Threads

![Screenshot 2024-01-04 at 2 20 43 AM](https://github.com/lil-lab/recnet/assets/71842426/72eef40d-d2e8-4394-8dc6-99c8f146e3cf)

It's dark mode by default. Personally, I like dark mode, it's easier to read in my opinion, but it's not for everyone. If we are gonna redesign the UI (#80), we need to figure out which mode we will start working on first(light or dark).

**Comment by joannechen1223** [comment]
[Medium](https://medium.com/)

<img width="1440" alt="Screenshot 2024-01-05 at 11 51 43 AM" src="https://github.com/lil-lab/recnet/assets/22555930/a4ec98ef-b9d0-478b-b12d-dbff1e9eedd9">
<img width="1437" alt="Screenshot 2024-01-05 at 11 54 41 AM" src="https://github.com/lil-lab/recnet/assets/22555930/bef14f7b-5ca1-4999-b476-0451f9cbc79f">

**Comment by anya-ji** [comment]
[Quora](https://www.quora.com/)
<img width="1664" alt="Screen Shot 2024-01-08 at 20 53 26" src="https://github.com/lil-lab/recnet/assets/61763411/f2159747-8da4-4b38-b1f2-65f1a97a464b">
<img width="1548" alt="Screen Shot 2024-01-08 at 20 54 27" src="https://github.com/lil-lab/recnet/assets/61763411/f3ba14d5-7a1e-481d-9d6b-22009d773e7a">
Some useful design takeaways:
- Upvote/downvote
- Credentials/affiliation/fields column (on the right of the profile)
- Notify Me (set notification for a specific user)
